### ISSUE TITLE
Unable to add peers to the cluster

### ISSUE THREAD

**Issue by sac** [gluster/python-gluster-mgmt-client#16]
Unable to add peers to the cluster. When I follow the documenation, I see the below traceback:

```
>>> from glusterapi import Client
>>> client = Client("10.70.41.250")
>>> client.peer_add("10.70.43.250")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "glusterapi/peer.py", line 28, in peer_add
    json.dumps(req))
  File "glusterapi/common.py", line 87, in _handle_request
    resp = func(*args, **kwargs)
  File "glusterapi/common.py", line 73, in _post
    verify=self.verify)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '10.70.41.250/v1/peers': No schema supplied. Perhaps you meant http://10.70.41.250/v1/peers?
```

**Comment by Madhu-1** [comment]
@sac, Client should be created as below

```
client=Client("http://127.0.0.1:24007")
```
we need to update documentation.

**Comment by sac** [comment]
@Madhu-1 even with that I see:

```
>>> from glusterapi import Client
>>> client = Client("http://10.70.41.250:24007")
>>> client.peer_add("10.70.43.250")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "glusterapi/peer.py", line 28, in peer_add
    json.dumps(req))
  File "glusterapi/common.py", line 90, in _handle_request
    raise GlusterApiError()
glusterapi.exceptions.GlusterApiError
>>> 
```

**Comment by Madhu-1** [comment]
@sac  host should be of the form ip:port ``` client.peer_add("10.70.43.250:24007")```

**Comment by devyanikota** [comment]
@sac @Madhu-1 should we keep the issue open?
I think we can add the ip validations before executing, to avoid similar issues?

**Comment by Madhu-1** [comment]
@devyanikota we need to validate endpoint while creating Client.
